name: Playwright E2E Tests with Allure Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
    env:
      HEADLESS: "false"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run tests for ${{ matrix.browser }}
        run: |
          source venv/bin/activate
          export HEADLESS=true
          pytest --browser_name=${{ matrix.browser }} --alluredir=allure-results/${{ matrix.browser }}

      - name: Upload Allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results-${{ matrix.browser }}
          path: allure-results/${{ matrix.browser }}

  allure-report:
    runs-on: ubuntu-latest
    needs: test  # ждём завершения всех job по браузерам

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Allure results artifacts
        uses: actions/download-artifact@v3
        with:
          name: allure-results-chromium
          path: allure-results/chromium
      - uses: actions/download-artifact@v3
        with:
          name: allure-results-firefox
          path: allure-results/firefox
      - uses: actions/download-artifact@v3
        with:
          name: allure-results-webkit
          path: allure-results/webkit

      - name: Merge Allure results
        run: |
          mkdir -p merged-results
          cp -r allure-results/*/* merged-results/ || true

      - name: Generate Allure report
        run: |
          npm install -g allure-commandline --save-dev
          allure generate merged-results -o allure-report --clean

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
